variables:
  GIT_SSL_NO_VERIFY: 1
  API_URL_CI: "https://toto.insee.fr"

stages:
  - install
  - lint
  - prebuild
  - build
  - docker
  - deploy

test-install:
  stage: install
  tags:
    - npm
  script:
    - 'yarn'

linter:
  stage: lint
  tags:
    - npm
  script:
    - 'yarn'
    - 'yarn lint'

generate-conf:
  stage: prebuild
  image: bhgedigital/envsubst
  script: 
    - envsubst < .ci/configuration/template/configuration.json > .ci/configuration/configuration.json
    - envsubst < .ci/configuration/template/keycloak.json > .ci/configuration/keycloak.json
    - cat .ci/configuration/keycloak.json
    - cat .ci/configuration/configuration.json
  artifacts:
   paths:
    - .ci
   expire_in: 30 minutes

build:
  stage: build
  tags:
    - npm
  script:
    - yarn
    - yarn build
  artifacts:
   paths:
    - build
   expire_in: 30 minutes
    
build-docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - export HTTP_PROXY=http://proxy-rie.http.insee.fr:8080
    - export HTTPS_PROXY=http://proxy-rie.http.insee.fr:8080
    - export NO_PROXY=".insee.test,.insee.eu,.insee.fr,.intra,.mesos,.thisdcos.directory,.dcos.directory,.zk,127.0.0.1,localhost"~
    - /kaniko/executor --context . --dockerfile Dockerfile --destination docker-registry.beta.innovation.insee.eu/outils-transverses/services-annuaire/sugoi/sugoi-js:${CI_COMMIT_REF_SLUG} --skip-tls-verify
  except:
    - tags

deploy review on Marathon:
  stage: deploy
  image: rija/docker-alpine-shell-tools
  variables:
    APP_ID: /outils-transverses/services-annuaire/sugoi/sugoi-js/$CI_COMMIT_REF_SLUG
    HAPROXY: $CI_PROJECT_ID-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.dev.innovation.insee.eu
    REVIEW_IMAGE: docker-registry.beta.innovation.insee.eu/outils-transverses/services-annuaire/sugoi/sugoi-js:${CI_COMMIT_REF_SLUG}
  script:
    - 'envsubst < .ci/marathon/marathon.json'
    - 'envsubst < .ci/marathon/marathon.json | curl -d@- -H "Content-Type: application/json" -X PUT http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID?force=true'
    - 'curl -X POST http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID/restart?force=true'
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    url: http://$CI_PROJECT_ID-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.dev.innovation.insee.eu
    on_stop: stop_review on marathon
  except:
    - tags
    - /^.*dependabot.*$/

stop_review on marathon:
  stage: deploy
  variables:
    GIT_STRATEGY: none
    APP_ID: /outils-transverses/services-annuaire/sugoi/sugoi-js/$CI_COMMIT_REF_SLUG
  script:
    - 'curl -X DELETE http://deploy.alpha.innovation.insee.eu/v2/apps/$APP_ID'
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_SLUG
    action: stop
  except:
    - tags
    - /^.*dependabot.*$/